---
- name: update apt packages
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes 
  apt:
    upgrade: yes
    
- name :  remove dependencies that are no longer required
  become: yes  
  apt:
    autoremove: yes

- name :   Install NPM 
  become : yes
  apt:
    name : npm
    update_cache : yes

- name: install NVM    
  shell: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

- name: source bashrc
  sudo: no   
  shell: ./home/username/.bashrc && nvm install v16.8.0   
                              
- name: Install PM2
  become : yes
  npm :
    name: pm2
    global : yes
    production : yes
    state : present

    