---

- name: install and pin nodejs at 16.8.0
  win_chocolatey:
    name: nodejs
   
- name: "Install PM2"
  become : yes
  npm :
    name: pm2
    global : yes
    production : yes
    state : present