---

- name: update apt packages
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes 
  apt:
    upgrade: yes
    
- name :  remove dependencies that are no longer required
  become: yes  
  apt:
    autoremove: yes

- name : Install dependencies 
  become : yes
  apt:
    name : "npm"
    state : latest
    update_cache : yes
    

- name: "Install Node.js 13"
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Use n version manager to switch to Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0   
   
- name: "Install PM2"
  become : yes
  npm :
    name: pm2
    global : yes
    production : yes
    state : present