---

- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes 
  apt:
    upgrade: yes
    
- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes


- name: "install NVM"
  shell: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

- name: source bashrc
  shell: source /home/username/.bashrc && nvm install v16.8.0
  args:
     executable: /bin/bash

- name: "Install PM2"
  become : yes
  npm :
    name: pm2
    global : yes
    production : yes
    state : present