---
- name: update apt packages
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes 
  apt:
    upgrade: yes
    
- name :  remove dependencies that are no longer required
  become: yes   
  apt:
    autoremove: yes

- name :   Install dependencies 
  become : yes
  apt:
    name : ["nodejs=13.8.0","npm"]
    
- name: Install PM2
  become : yes
  npm :
    name: pm2
    global : yes
    production : yes
    state : present

- name: Extract artifact.tar.gz 
  unarchive:
    src: artifact.tar.gz
    dest: ~/     

- name: Executing node    
  shell: |
        cd backend
        npm install
        pm2 stop default
        pm2 start npm -- start

