---
- name: update apt packages
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes 
  apt:
    upgrade: yes
    
- name :  remove dependencies that are no longer required
  become: yes   
  apt:
    autoremove: yes

- name :   Install dependencies 
  become : yes
  apt:
    name : ["nodejs","npm"]
    state : latest
    update_cache : yes

- name: Install PM2
  become : yes
  npm :
    name: pm2
    global : yes
    production : yes
    state : present

- name : Create Directory
  file :
     path : ~/web
     state : directory

- name : copy artifact to server 
  template:
     src: ~/artifact.tar.gz
     dest : ~/

- name: Executing node    
  shell: |
        $ tar xvzf artifact.tar.gz
        npm install
        pm2 stop default
        pm2 start npm -- start

