---

- name: install NVM    
  shell: |
      nvm install v16.8.0

      
- name : Create Directory
  file :
     path : ~/web
     state : directory

- name: Extract artifact.tar.gz 
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: Executing node    
  shell: |
        cd  ~/web/backend
        npm install
        pm2 stop default
        pm2 start npm -- start

