---

- name : Create Directory
  file :
     path : ~/web
     state : directory


- name: Extract artifact.tar.gz 
  unarchive:
    src: artifact.tar.gz
    dest: ~/web

- name: Executing node Application with PM2
  shell: |
        cd  ~/web/dist
        npm install
        pm2 stop default
        pm2 start main.js
  register: execute_node      

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"
