---
- name: Extract artifact.tar.gz 
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/     

- name: Executing node    
  shell: |
        cd backend
        npm install
        pm2 stop default
        pm2 start npm -- start

